name: Continous Integration Automation
on:
  push:
    branches:
      - main
jobs:
    run_auto:
      runs-on: ubuntu-18.04
      steps:
        - name: Move to branch
          uses: actions/checkout@v3
          with:
            fetch-depth: 0
        - name: Setup node
          uses: actions/setup-node@v3.5.1
        - name: Install dependencies
          run: npm install
        - name: Run Test with webdio
          env:
            KEY: ${{ secrets.KEY }}
            PASSWORD: ${{ secrets.PASSWORD }}
            SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
            SLACK_CHANNEL: ${{ secrets.SLACK_CHANNEL }}
            WEB_API: ${{ secrets.WEB_API }}
            BROWSERSTACK_USERNAME: ${{ secrets.BROWSERSTACK_USERNAME }}
            BROWSERSTACK_ACCESS_KEY: ${{ secrets.BROWSERSTACK_ACCESS_KEY }}
          run: npm test