name: Hello test
on:
  push:
    branches:
      - premortem
jobs:
    run_auto:
      runs-on: ubuntu-18.04
      steps:
        - name: Install dependencies
        - run: npm install
        - name: Run Test with webdio
        - run: npm run test