name: Hello test
on:
  push:
    branches:
      - premortem
jobs:
    run_auto:
      runs-on: ubuntu-18.04
      steps:
        - name: moverse a branches
          uses: actions/checkout@v3
          with:
            fetch-depth: 0
        - name: Setup node
          uses: actions/setup-node@3.5.1
        - name: Install dependencies
          run: npm install
        - name: Run Test with webdio
          env:
            KEY: ${{ secrets.KEY }}
            PASSWORD: ${{ secrets.PASSWORD }}
            SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
            SLACK_CHANNEL: ${{ secrets.SLACK_CHANNEL }}
            WEB_API: ${{ secrets.WEB_API }}
          run: npm test
        # - uses: actions/upload-artifact@v1
        #   if: failure()
        #   with:
        #     name: logs
        #     path: logs
        # - name: list elements
        #   run: ls