name: Hello test
on:
  push:
    branches:
      - premortem
jobs:
    run_auto:
      runs-on: ubuntu-18.04
      steps:
        - name: moverse a branches
          uses: actions/checkout@v2
          with:
            fetch-depth: 0
        - name: Install dependencies
          run: npm install
        - name: Run Test with webdio
          run: npmtest
        - uses: actions/upload-artifact@v1
          if: failure()
          with:
            name: logs
            path: logs
        # - name: list elements
        #   run: ls